import os, subprocess, time, json, urllib.request, shutil
from playwright.sync_api import sync_playwright
SCR=os.environ.get('SCR', os.path.join(os.path.dirname(os.path.abspath(__file__)), 'tmp')); os.makedirs(SCR, exist_ok=True)
FIX=os.environ.get('FIXTURES', os.path.join(os.path.dirname(os.path.abspath(__file__)), 'fixtures'))
APP=os.path.dirname(os.path.dirname(os.path.abspath(__file__))); PORT='3778'; DATA=f'{SCR}/uidata'
shutil.rmtree(DATA,ignore_errors=True)
env=dict(os.environ,DATA_DIR=DATA,PORT=PORT)
srv=subprocess.Popen(['node','server.js'],cwd=APP,env=env,stdout=subprocess.DEVNULL,stderr=subprocess.DEVNULL)
time.sleep(1.2)
BASE=f'http://localhost:{PORT}'
fails=[]; shots=[]
def ok(name,cond):
    print(('  ✓ ' if cond else '  ✗ ')+name)
    if not cond: fails.append(name)
try:
    with sync_playwright() as p:
        b=p.chromium.launch(**({'executable_path': os.environ['CHROME']} if os.environ.get('CHROME') else {}))
        ctx=b.new_context(viewport={'width':1280,'height':800})
        page=ctx.new_page(); errors=[]
        page.on('pageerror',lambda e:errors.append(str(e)))
        page.on('console',lambda m:errors.append(m.text) if m.type=='error' else None)
        page.goto(BASE); page.wait_for_selector('form')
        ok('setup screen shown','Первый запуск' in page.content())
        page.fill('input[name=name]','Мейр'); page.fill('input[name=login]','meir'); page.fill('input[name=password]','secret123')
        page.click('button[type=submit]'); page.wait_for_selector('#nav',timeout=8000)
        ok('logged in, nav visible',page.locator('#nav a').count()>=10)
        # seed via settings
        page.goto(BASE+'/#/settings'); page.wait_for_selector('[data-act=seed]',timeout=8000)
        page.once('dialog',lambda d:d.accept()); page.click('[data-act=seed]')
        page.wait_for_function("document.querySelector('#toast') && !document.querySelector('#toast').hidden",timeout=10000)
        ok('seed toast',True)
        time.sleep(0.6)
        for sec in ['dashboard','ops','docs','invoices','projects','contracts','subcontracts','proposals','payroll','obligations','settings']:
            page.goto(BASE+'/#/'+sec); time.sleep(0.7)
            txt=page.locator('#main').inner_text()
            ok(f'section {sec} rendered','Загрузка…' not in txt and len(txt)>20)
            if sec in ('dashboard','docs','invoices'):
                f=f'{SCR}/shot-{sec}.png'; page.screenshot(path=f,full_page=False); shots.append(f)
        # ops: inline category edit
        page.goto(BASE+'/#/ops?year=2026&untagged=1'); time.sleep(1.0)
        ok('ops untagged rows shown', page.locator('tbody tr').count()>10)
        page.locator('.cell-edit.auto').first.click(); time.sleep(0.3)
        ok('inline select appears', page.locator('tbody select').count()==1)
        page.locator('tbody select').first.select_option(index=2); time.sleep(0.8)
        ok('inline edit saved (row re-rendered)', page.locator('tbody select').count()==0)
        f=f'{SCR}/shot-ops.png'; page.screenshot(path=f); shots.append(f)
        page.goto(BASE+'/#/projects'); time.sleep(0.8); f=f'{SCR}/shot-projects.png'; page.screenshot(path=f); shots.append(f)
        page.goto(BASE+'/#/contracts'); time.sleep(0.8); f=f'{SCR}/shot-contracts.png'; page.screenshot(path=f); shots.append(f)
        # ops filters: сортировка и период
        page.goto(BASE+'/#/ops?from=2026-08-01&to=2026-08-31&company=MOST%20Project&min=1000000'); time.sleep(1.0)
        n1=page.locator('tbody tr').count(); ok('ops range+company+min filter', 0<n1<200)
        page.locator('th.sortable[data-sort=debit]').click(); time.sleep(0.9)
        ok('sort by debit desc', 'sort=debit' in page.evaluate('location.hash') and page.locator('th.sorted').count()==1)
        ok('reset button present', page.locator('[data-act=reset]').count()==1)
        # выписка PDF
        page.goto(BASE+'/#/ops'); time.sleep(0.8); page.click('[data-act=stmt]'); page.wait_for_selector('#stmt-file')
        page.set_input_files('#stmt-file',os.path.join(FIX, 'kaspi-statement.pdf'))
        page.wait_for_selector('#stmt-go', timeout=60000); time.sleep(0.5)
        txt=page.locator('#stmt-out').inner_text(); print('   выписка:', txt[:200].replace('\n',' | '))
        ok('statement parsed: account guessed MOST', page.locator('#stmt-acc').input_value()=='MOST')
        ok('statement: all 396 ops recognised as duplicates of budget data', 'дубликатов пропущено 396' in txt and 'сходится' in txt)
        page.select_option('#stmt-acc','PANA'); page.wait_for_function("/Загрузить 39\\d операций/.test(document.querySelector('#stmt-go') ? document.querySelector('#stmt-go').innerText : '')", timeout=30000); time.sleep(0.3)
        ok('statement: other account → ~396 new ops', True)
        f=f'{SCR}/shot-stmt.png'; page.screenshot(path=f); shots.append(f)
        page.click('#stmt-go'); page.wait_for_selector('#modal', state='hidden', timeout=60000); time.sleep(1.0)
        ok('statement imported → untagged view', 'untagged=1' in page.evaluate('location.hash') and page.locator('tbody tr').count()>10)
        # ЗП: вкладки
        # invoices: import from xlsx + pdf, attach & preview
        page.goto(BASE+'/#/invoices'); time.sleep(0.7); page.click('[data-act=invImport]'); page.wait_for_selector('#inv-files')
        page.set_input_files('#inv-files', [os.path.join(FIX, 'invoices-register.xlsx'), os.path.join(FIX, 'invoice.pdf')])
        page.wait_for_selector('#inv-go', timeout=20000); n_rows = page.locator('#inv-out tbody tr').count()
        ok('invoice import preview rows', n_rows >= 17)
        ok('pdf invoice parsed', 'Eservice' in page.locator('#inv-out').inner_text() or page.locator('.inv-cp[value*="Eservice"]').count() > 0)
        page.click('#inv-go'); time.sleep(2.0); page.wait_for_selector('#modal', state='hidden', timeout=15000)
        page.goto(BASE+'/#/invoices?status=all&text=Eservice'); time.sleep(0.8)
        ok('imported invoice listed with file chip', page.locator('.file-chip').count() >= 1)
        page.click('tr.row-click'); page.wait_for_selector('#modal:not([hidden]) iframe.preview-frame', timeout=5000); ok('invoice file preview opens', True)
        page.keyboard.press('Escape'); time.sleep(0.3)
        page.goto(BASE+'/#/ops?year=2026'); time.sleep(0.9); th = page.locator('thead').inner_text()
        ok('ops table has opNo and comment columns', '№' in th and 'КОММЕНТАРИЙ' in th.upper())
        ok('real logo in sidebar', page.locator('.brand .logo svg path').count() >= 1 and page.evaluate("document.querySelector('.brand .logo svg').getAttribute('viewBox')") == '0 30 143 128')
        f=f'{SCR}/shot-invoices.png'; page.goto(BASE+'/#/invoices?status=all'); time.sleep(0.8); page.screenshot(path=f); shots.append(f)
        # payment calendar, reports, obligations → invoices, xlsx statement, restore UI
        page.goto(BASE+'/#/invoices?view=calendar'); time.sleep(0.8); ok('payment calendar renders', 'Платёжный календарь' in page.locator('#main').inner_text() and page.locator('.tabs a.active').inner_text().startswith('Платёжный'))
        page.goto(BASE+'/#/obligations'); time.sleep(0.7); page.click('[data-act=oblInvoices]'); page.wait_for_selector('#modal input[name=ym]'); page.fill('#modal input[name=ym]', '2026-11'); page.click('#modal button[type=submit]'); time.sleep(1.2)
        ok('obligations → calendar with invoices', 'Платёжный календарь' in page.locator('#main').inner_text() and page.locator('.due-inline').count() >= 5)
        page.goto(BASE+'/#/reports?year=2026'); time.sleep(0.9); t = page.locator('#main').inner_text(); ok('reports page', 'По месяцам' in t and 'Сентябрь 2026' in t and 'Расходы по категориям' in t)
        page.goto(BASE+'/#/ops'); time.sleep(0.8); page.click('[data-act=stmt]'); page.wait_for_selector('#stmt-file'); page.set_input_files('#stmt-file', os.path.join(FIX, 'statement.xlsx')); page.wait_for_selector('#stmt-go', timeout=15000)
        ok('xlsx statement parsed 3 ops', '3' in page.locator('#stmt-out .card').nth(1).inner_text() and 'Рога и Копыта' in page.locator('#stmt-out').inner_text())
        page.keyboard.press('Escape'); time.sleep(0.3)
        page.goto(BASE+'/#/dashboard'); time.sleep(0.8); t = page.locator('#main').inner_text(); ok('dashboard balances tile', 'На счетах (по операциям)' in t and 'не согласовано' in t)
        page.goto(BASE+'/#/contracts'); time.sleep(0.8); ok('contracts file column', page.locator('[data-act=fileAttach][data-col=contracts]').count() > 5)
        page.goto(BASE+'/#/settings'); time.sleep(0.8); ok('restore UI for owner', page.locator('#restore-file').count() == 1 and 'Расчёт по операциям' in page.locator('#main').inner_text())
        # counterparties, project card, KP generator, allocation modal
        page.goto(BASE+'/#/counterparties'); time.sleep(0.8); page.click('[data-act=cpRebuild]'); time.sleep(1.5)
        ok('counterparties built', page.locator('tbody tr').count() > 50)
        page.goto(BASE+'/#/contracts'); time.sleep(0.9); ok('contracts link to project card', page.locator('tbody a[href^="#/project?id="]').count() > 50)
        page.locator('tbody a[href^="#/project?id="]').first.click(); time.sleep(0.9); t = page.locator('#main').inner_text()
        ok('project card renders', 'Стадии' in t and 'Договоры с заказчиком' in t and 'Маржа факт' in t)
        page.click('[data-act=stageAdd]'); page.wait_for_selector('#modal input[name=name]'); page.fill('#modal input[name=name]', 'Эскизный проект'); page.fill('#modal input[name=planSum]', '12000000'); page.fill('#modal input[name=progress]', '30'); page.click('#modal button[type=submit]'); time.sleep(0.9)
        ok('stage added to card', page.locator('tbody tr').count() >= 1 and '30%' in page.locator('#main').inner_text())
        page.goto(BASE+'/#/proposals'); time.sleep(0.8); ok('KP template buttons', page.locator('[data-act=kpNew][data-tpl=ep]').count() >= 1)
        page.locator('[data-act=kpNew][data-tpl=ep]').first.click(); page.wait_for_selector('#kp-form'); page.fill('#kp-form input[name=object]', 'ЖК Тест'); page.fill('#kp-form textarea[name=areas]', 'Коммерция | 2000 | | 1\nЖильё | 140000 | | 1\nПаркинг | 38000 | | 0.5')
        page.dispatch_event('#kp-form textarea[name=areas]', 'input'); time.sleep(0.3); tot = page.locator('#kp-total').inner_text(); ok('KP total computed', '169' in tot.replace('\u00a0', '') and '₸' in tot)
        page.click('#kp-preview'); time.sleep(0.6); ok('KP preview iframe', page.locator('#kp-frame').count() == 1 and page.frame_locator('#kp-frame').locator('h1').inner_text().startswith('КОММЕРЧЕСКОЕ'))
        page.click('#kp-form button[type=submit]'); time.sleep(0.9); ok('KP saved on proposal', page.locator('[data-act=kpOpen]').count() >= 1)
        page.locator('[data-act=kpNew][data-tpl=an]').first.click() if page.locator('[data-act=kpNew][data-tpl=an]').count() else None; time.sleep(0.5)
        if page.locator('#kp-form').count(): ok('AN template fixed mode', page.locator('#kp-form textarea[name=items]').count() == 1); page.keyboard.press('Escape'); time.sleep(0.3)
        page.goto(BASE+'/#/ops'); time.sleep(0.8); page.click('[data-act=allocate]'); page.wait_for_selector('#al-go', timeout=10000); n_al = page.locator('.al-pick').count(); ok('allocation modal lists proposals', n_al >= 10)
        page.click('#al-go'); time.sleep(1.2); ok('allocation applied → ops list', 'kind=income' in page.url or page.locator('tbody tr').count() > 0)
        # секретарь
        sp = ctx.new_page(); sp.goto(BASE+'/#/settings'); time.sleep(0.8)
        sp.click('[data-act=userAdd]'); sp.wait_for_selector('#modal input[name=login]'); sp.fill('#modal input[name=name]', 'Айгерим'); sp.fill('#modal input[name=login]', 'aigerim'); sp.select_option('#modal select[name=role]', 'secretary'); sp.fill('#modal input[name=password]', 'secret123'); sp.click('#modal button[type=submit]'); time.sleep(0.8); sp.close()
        sc = b.new_context(viewport={'width':1280,'height':800}); s2 = sc.new_page(); s2.goto(BASE); s2.wait_for_selector('form'); s2.fill('input[name=login]','aigerim'); s2.fill('input[name=password]','secret123'); s2.click('button[type=submit]'); s2.wait_for_selector('#nav', timeout=8000); time.sleep(0.6)
        navt = s2.locator('#nav').inner_text(); ok('secretary nav: no dashboard, has ops/payroll/contracts/proposals', 'Дашборд' not in navt and 'Операции' in navt and 'ЗП' in navt and 'Договоры' in navt and 'Коммерческие' in navt and 'Контрагенты' in navt)
        s2.goto(BASE+'/#/docs'); time.sleep(0.7); ok('secretary can create doc request', s2.locator('[data-act=docAdd]').count() == 1)
        s2.goto(BASE+'/#/contracts'); time.sleep(0.8); ok('secretary contracts with fact column', s2.locator('[data-act=add]').count() == 1 and 'ФАКТ ПО ОПЕРАЦИЯМ' in s2.locator('thead').inner_text().upper())
        sc.close()
        page.goto(BASE+'/#/payroll'); time.sleep(0.9)
        ok('payroll months table', page.locator('tr.row-click').count()>=6)
        ok('payroll first month expanded with lines', page.locator('tr.row-detail tbody tr').count()>30)
        page.goto(BASE+'/#/payroll?tab=employees'); time.sleep(0.8); ok('employees tab', page.locator('tbody tr').count()>30 and 'отпуск' in page.locator('thead').inner_text().lower())
        page.goto(BASE+'/#/payroll?tab=vacations&cal=2026-03'); time.sleep(0.8); ok('vacation calendar', page.locator('table.cal').count()==1 and page.locator('td.cal-cell').count()>500)
        page.click('[data-act=vacAdd]'); page.wait_for_selector('#modal form'); page.fill('#modal input[name=from]','2026-03-16'); page.fill('#modal input[name=to]','2026-03-29'); page.click('#modal button[type=submit]'); time.sleep(0.9)
        ok('vacation added → colored cells', page.locator('td.cal-cell.vac-v').count()==14)
        f=f'{SCR}/shot-vacations.png'; page.screenshot(path=f); shots.append(f)
        # dashboard numbers
        page.goto(BASE+'/#/dashboard'); time.sleep(0.7); t=page.locator('#main').inner_text()
        ok('dashboard has cash & queue tiles','На счетах' in t and 'Очередь' in t)
        # create doc request via modal
        page.goto(BASE+'/#/docs'); page.wait_for_selector('[data-act=docAdd]'); page.click('[data-act=docAdd]')
        page.wait_for_selector('#modal form'); page.fill('#modal input[name=client]','Everest'); page.fill('#modal textarea[name=description]','Акт по Алмеу'); page.fill('#modal input[name=amount]','46888030')
        page.click('#modal button[type=submit]'); time.sleep(0.8)
        ok('doc card created','Everest' in page.locator('#main').inner_text() and page.locator('.q-card').count()>=1)
        ok('badge shows 1',page.locator('#badge-docs').inner_text().strip()=='1')
        page.click('.q-card [data-act=docStatus][data-status=in_progress]'); time.sleep(0.6)
        ok('status → в работе','В работе' in page.locator('.q-card').first.inner_text())
        # invoices: mark paid
        page.goto(BASE+'/#/invoices'); time.sleep(0.7)
        n_before=page.locator('tbody tr').count()
        page.locator('tbody tr').first.locator('[data-act=invStatus][data-status=paid]').click(); time.sleep(0.7)
        ok('invoice marked paid (row left open list)',page.locator('tbody tr').count()==n_before-1)
        # mobile: no horizontal scroll
        m=b.new_context(viewport={'width':390,'height':800}); mp=m.new_page()
        mp.goto(BASE); mp.wait_for_selector('form'); mp.fill('input[name=login]','meir'); mp.fill('input[name=password]','secret123'); mp.click('button[type=submit]'); mp.wait_for_selector('#main',timeout=8000)
        mp.goto(BASE+'/#/dashboard'); time.sleep(0.8)
        sw=mp.evaluate('document.documentElement.scrollWidth'); iw=mp.evaluate('window.innerWidth')
        ok(f'mobile no horizontal scroll ({sw}<={iw})',sw<=iw)
        mp.click('#burger'); time.sleep(0.3); ok('mobile menu opens',mp.locator('#side.open').count()==1)
        f=f'{SCR}/shot-mobile.png'; mp.screenshot(path=f); shots.append(f)
        # dark theme
        d=b.new_context(viewport={'width':1280,'height':800},color_scheme='dark'); dp=d.new_page()
        dp.goto(BASE); dp.wait_for_selector('form'); dp.fill('input[name=login]','meir'); dp.fill('input[name=password]','secret123'); dp.click('button[type=submit]'); dp.wait_for_selector('#main',timeout=8000)
        dp.goto(BASE+'/#/dashboard'); time.sleep(0.8); bg=dp.evaluate("getComputedStyle(document.body).backgroundColor")
        ok(f'dark theme applied ({bg})',bg!='rgb(244, 246, 248)')
        f=f'{SCR}/shot-dark.png'; dp.screenshot(path=f); shots.append(f)
        # PM limited view
        req=urllib.request.Request(BASE+'/api/users',data=json.dumps({'login':'pm','password':'secret123','name':'ПМ','role':'pm'}).encode(),headers={'Content-Type':'application/json','X-Requested-With':'fetch','Cookie':'; '.join(f"{c['name']}={c['value']}" for c in ctx.cookies())},method='POST')
        urllib.request.urlopen(req).read()
        pc=b.new_context(viewport={'width':1280,'height':800}); pp=pc.new_page()
        pp.goto(BASE); pp.wait_for_selector('form'); pp.fill('input[name=login]','pm'); pp.fill('input[name=password]','secret123'); pp.click('button[type=submit]'); pp.wait_for_selector('#nav',timeout=8000)
        ok('pm sees only 7 nav items',pp.locator('#nav a').count()== 7)
        pp.goto(BASE+'/#/docs'); time.sleep(0.6)
        ok('pm has no add button',pp.locator('[data-act=docAdd]').count()==0 and pp.locator('[data-act=docStatus]').count()==0)
        pp.goto(BASE+'/#/ops'); time.sleep(0.6)
        ok('pm ops → falls back',  'Операции' not in (pp.locator('#main h1').inner_text() if pp.locator('#main h1').count() else ''))
        f=f'{SCR}/shot-pm.png'; pp.screenshot(path=f); shots.append(f)
        ok('no JS errors', not errors)
        if errors: print('   errors:',errors[:5])
        b.close()
finally:
    srv.terminate()
print('\nFAILS:',fails if fails else 'none'); print('SHOTS:',shots)
